import os

class Config:
    base_model_name = "EleutherAI/gpt-neo-125M"
    base_model_basename = base_model_name.split("/")[1]
    work_dir = os.path.join("/opt", "awsw")
    interactable_characters = {
        "Ad": "Adine",
        "An": "Anna",
        "Br": "Bryce",
        "Dm": "Damion",
        "Em": "Emera",
        "Ip": "Ipsum",
        "Iz": "Izumi",
        "Ka": "Katsuharu",
        "Kv": "Kevin",
        "Lo": "Lorem",
        "Mv": "Maverick",
        "Nm": "Naomi",
        "Ry": "Remy",
        "Rz": "Reza",
        "Sb": "Sebastian",
        "Zh": "Zhong",
    }
    valid_emotions_for_dragon = {
        "Ry": ["normal", "smile", "shy", "sad", "look", "angry", "face", "think"],
        "Lo": ["shy", "happy", "normal", "relieved", "think", "sad"],
        "Ip": ["happy", "think", "normal", "sad"],
        "Br": [
            "normal",
            "stern",
            "smirk",
            "brow",
            "laugh",
            "flirty",
            "gunself",
            "angry",
            "shy",
            "sad",
        ],
        "An": [
            "normal",
            "sad",
            "face",
            "disgust",
            "rage",
            "smirk",
            "cry",
            "despair",
            "think",
        ],
        "Mv": [
            "scared",
            "normal",
            "angry",
            "nice",
            "sad",
            "think",
            "rage",
            "laugh",
            "annoyed",
            "smile",
            "shy",
            "sideeye",
        ],
        "Ad": ["think", "normal", "giggle", "annoyed", "disappoint", "sad", "frustrated"],
        "Em": ["mean", "frown", "normal", "ques", "laugh", "stern"],
        "Sb": ["normal", "drop", "disapproval", "brow", "stern", "smile", "shy", "hand"],
        "Dm": ["arrogant", "face", "normal"],
        "Ka": ["normal", "exhausted", "smile", "excited", "ques"],
        "Rz": [
            "angry",
            "annoyed",
            "gunpoint",
            "normal",
            "amused",
            "gunself",
            "rage",
            "defeat",
            "laugh",
        ],
        "Iz": ["normal"],
        "Zh": ["normal", "smile", "serv", "shy", "laugh"],
        "Kv": ["ramble", "normal", "brow", "face"],
        "Nm": [
            "smile",
            "shy",
            "normal",
            "blank",
            "stern",
            "scared",
            "confused",
            "cry",
            "angry",
            "sad",
            "concern",
            "annoyed",
            "hurt",
            "crysmile",
            "sleep",
            "slsmile",
            "giggle",
            "bacon",
        ],
    }
