version: "2.3"

services:
  endless_awsw_research:
    build: ./Docker
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "./:/opt/awsw"
    ports:
      - "127.0.0.1:8888:8888"
