version: "3"
services:
  endless_server:
    build: .
    volumes:
      - "./src:/opt/awsw"
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    ports:
      - "0.0.0.0:5000:5000"
