version: "3"
services:
  data_extractor:
    build:
      context: "./"
    volumes:
      - "../src:/src/extractor"
      - "../../Angels with Scaly Wings:/src/awsw"
    ports:
      - 127.0.0.1:8922:8080
